src/main/java/org/springframework/samples/petclinic/model/Vet.java
/*
 * Copyright 2002-2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.samples.petclinic.model;

import java.util.ArrayList;
import java.util.Collections;
import java.util.HashSet;
import java.util.List;
import java.util.Set;

import javax.persistence.*;
import javax.xml.bind.annotation.XmlElement;

import org.hibernate.validator.constraints.NotEmpty;
import org.springframework.beans.support.MutableSortDefinition;
import org.springframework.beans.support.PropertyComparator;

/**
 * Simple JavaBean domain object representing a veterinarian.
 *
 * @author Ken Krebs
 * @author Juergen Hoeller
 * @author Sam Brannen
 * @author Arjen Poutsma
 */
@Entity
@Table(name = "vets")
public class Vet extends Person {

    @ManyToMany(fetch = FetchType.EAGER)
    @JoinTable(name = "vet_specialties", joinColumns = @JoinColumn(name = "vet_id"),
            inverseJoinColumns = @JoinColumn(name = "specialty_id"))
    private Set<Specialty> specialties;

    @Column(name = "days")
    @NotEmpty
    private String days;

    public String getDays() {
        return this.days;
    }

    public void setDays(String days) {
        this.days = days;
    }

    @Column(name = "email")
    @NotEmpty
    private String email;

    public String getEmail() {
        return this.email;
    }

    public void setEmail(String email) {
        this.email = email;
    }

    protected void setSpecialtiesInternal(Set<Specialty> specialties) {
        this.specialties = specialties;
    }

    protected Set<Specialty> getSpecialtiesInternal() {
        if (this.specialties == null) {
            this.specialties = new HashSet<Specialty>();
        }
        return this.specialties;
    }

    @XmlElement
    public List<Specialty> getSpecialties() {
        List<Specialty> sortedSpecs = new ArrayList<Specialty>(getSpecialtiesInternal());
        PropertyComparator.sort(sortedSpecs, new MutableSortDefinition("name", true, true));
        return Collections.unmodifiableList(sortedSpecs);
    }

    public int getNrOfSpecialties() {
        return getSpecialtiesInternal().size();
    }

    public void addSpecialty(Specialty specialty) {
        getSpecialtiesInternal().add(specialty);
    }

}

src/main/java/org/springframework/samples/petclinic/model/Vets.java
/*
/*
 * Copyright 2002-2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.samples.petclinic.model;

import java.util.ArrayList;
import java.util.List;

import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;

/**
 * Simple domain object representing a list of veterinarians. Mostly here to be used for the 'vets' {@link
 * org.springframework.web.servlet.view.xml.MarshallingView}.
 *
 * @author Arjen Poutsma
 */
@XmlRootElement
public class Vets {

    private List<Vet> vets;

    @XmlElement
    public List<Vet> getVetList() {
        if (vets == null) {
            vets = new ArrayList<Vet>();
        }
        return vets;
    }

}

src/main/java/org/springframework/samples/petclinic/web/VetController.java
/*
 * Copyright 2002-2013 the original author or authors.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package org.springframework.samples.petclinic.web;

import java.io.IOException;
import java.util.Map;
import java.util.UUID;

import org.springframework.beans.factory.annotation.Autowired;
import org.springframework.samples.petclinic.model.*;
import org.springframework.samples.petclinic.service.ClinicService;
import org.springframework.samples.petclinic.web.aspose.AsposeAPI;
import org.springframework.stereotype.Controller;
import org.springframework.validation.BindingResult;
import org.springframework.web.bind.annotation.*;
import org.springframework.web.bind.support.SessionStatus;

import javax.servlet.ServletOutputStream;
import javax.servlet.http.HttpServletRequest;
import javax.servlet.http.HttpServletResponse;

/**
 * @author Juergen Hoeller
 * @author Mark Fisher
 * @author Ken Krebs
 * @author Arjen Poutsma
 * @author Adeel Ilyas  (For Parts of Aspose APIs for Java, Spring Integration)
 */

@Controller
@SessionAttributes(types={Vets.class,EmailForm.class})
public class VetController {

    private final ClinicService clinicService;


    @Autowired
    public VetController(ClinicService clinicService) {
        this.clinicService = clinicService;
    }

    @RequestMapping("/vets")
    public String showVetList(Map<String, Object> model) {
        // Here we are returning an object of type 'Vets' rather than a collection of Vet objects 
        // so it is simpler for Object-Xml mapping
        Vets vets = new Vets();
        vets.getVetList().addAll(this.clinicService.findVets());
        model.put("vets", vets);
        return "vets/vetList";
    }

 /*
 * Project Extension Name: Aspose Java for Spring Java (petclinic)
 *
 * @author: Adeel Ilyas
 * Company: Aspose Pty Ltd.
 *
 * Date: 4/6/2014
 *
 * Detail:
 * This Extension was written to showcase the usage of Aspose APIs for Java
 * (Aspose.Word, Aspose.PDF, Aspose.Cells,Aspose.Email, Aspose Barcode)
 * for Spring, Spring MVC Java Developers.
 */

    @RequestMapping(value = "/vets/{typeFile}/export", method = RequestMethod.GET)
    public void processExport(@PathVariable("typeFile") String typeFile,Vets vets,HttpServletResponse response, HttpServletRequest req) {


        if (vets.getVetList().size()<1) {
            vets = new Vets();
            vets.getVetList().addAll(this.clinicService.findVets());
        }


        //tell browser program going to return an data file
        //instead of html page

        if (typeFile.equals("pdf")) {
            response.setContentType("application/pdf");
            response.setHeader("Content-Disposition","attachment;filename=AsposeExportVets.pdf");
        } else  if (typeFile.equals("cells")) {
            response.setContentType("application/vnd.ms-excel");
            response.setHeader("Content-Disposition","attachment;filename=AsposeExportVets.xlsx");
        } else  if (typeFile.equals("words")) {
            response.setContentType("application/msword");
            response.setHeader("Content-Disposition","attachment;filename=AsposeExportVets.doc");
        }

        try {
            ServletOutputStream out = response.getOutputStream();
            if (typeFile.equals("pdf")) {
                AsposeAPI.generateVetsAsposePDF(out, vets,req.getServletContext());
            } else  if (typeFile.equals("cells")) {
                AsposeAPI.generateVetsAsposeCells(out, vets,req.getServletContext());
            } else  if (typeFile.equals("words")) {
                AsposeAPI.generateVetsAsposeWords(out, vets,req.getServletContext());
            }

            out.close();

        } catch (Exception io) {
          io.printStackTrace();
        }

    }

    @RequestMapping(value = "/vet/{vetId}/email", method = RequestMethod.GET)
    public String initEmailVetForm(@PathVariable("vetId") int vetId,Map<String, Object> model) {
        Vet vet = this.clinicService.findVetById(vetId);
        EmailForm emailform = new EmailForm();
        emailform.setEmail(vet.getEmail());
        emailform.setSubject("Consultation");
        emailform.setFirstName(vet.getFirstName());
        emailform.setLastName(vet.getLastName());
        System.out.println(emailform.getFirstName()+" "+emailform.getLastName());
        model.put("emailform", emailform);
        return "vets/emailVet";
    }

    @RequestMapping(value = "/vet/{vetId}/email",method = {RequestMethod.PUT, RequestMethod.POST})
    public String processEmailVetForm(@ModelAttribute("emailform") EmailForm emailform,BindingResult result, SessionStatus status,HttpServletResponse response) {
        new EmailFormValidator().validate(emailform, result);
        if (result.hasErrors()) {
           return "vets/emailVet";
        } else {
            try {
                ServletOutputStream out = response.getOutputStream();
                response.setContentType("application/octet-stream");
                response.setHeader("Content-Disposition","attachment;filename="+emailform.getFirstName()+ UUID.randomUUID()+".msg");
                AsposeAPI.asposeEmail(emailform.getFirstName()+" "+emailform.getLastName(),emailform.getEmail(),emailform.getFrom(),emailform.getSubject(),emailform.getMessage(),out);
                out.flush();
                out.close();


                System.out.println("Message Sent: " + emailform.getMessage());

            } catch (IOException io) {

            }
            return "redirect:/vets";
        }
    }

}

src/main/webapp/WEB-INF/jsp/vets/emailVet.jsp
<!DOCTYPE html>
<!--
 * Project Extension Name: Aspose for Spring Java (petclinic)
 *
 * @author: Adeel Ilyas
 * Company: Aspose Pte Ltd.
 *
 * Date: 4/6/2014
 *
 * Detail:
 * This Extension was written to showcase the usage of Aspose APIs for Java
 * (Aspose.Word, Aspose.PDF, Aspose.Cells,Aspose.Email, Aspose Barcode)
 * for Spring, Spring MVC Java Developers.
 *
-->
<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@
taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib
prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>
<%@ taglib
prefix="form" uri="http://www.springframework.org/tags/form" %>
<%@
taglib prefix="petclinic" tagdir="/WEB-INF/tags" %>

<html lang="en">

	<jsp:include page="../fragments/headTag.jsp" />

	<body>
		<div class="container">
			<jsp:include page="../fragments/bodyHeader.jsp" />

			<h2>Email Veterinarian</h2>

			<table class="table table-striped" style="width:600px;height:100px">
				<tr>
					<th style="padding-right: 40px">Name</th>
					<td>
						<b>
							<c:out value="${emailform.firstName} ${emailform.lastName}" />
						</b>
					</td>

				</tr>
				<tr>
					<th>Email</th>
					<td>
						<b>
							<c:out value="${emailform.email}" />
						</b>
					</td>
				</tr>
			</table>

			<form:form modelAttribute="emailform" method="put"
				class="form-horizontal" id="send-vet-email">


				<table
					style="width:600px;border-collapse: separate;border-spacing: 5px 0px;">
					<tr>
						<td>
							<petclinic:inputField label="From" name="from" />
						</td>
					</tr>
					<tr>
						<td>
							<petclinic:inputField label="Subject" name="subject" />
						</td>
					</tr>
					<tr>
						<td>
							<label class="control-label">Message </label>
							<div class="controls">
								<form:textarea path="message" rows="7" cols="30" />
						</td>


		</div>
	</tr>
		<tr>

			<td>
				<div class="form-actions">

					<button type="submit" class="btn btn-success" ">Send from
						OutLook</button>

				</div>
			</td>
		</tr>
	</table>
	</form:form>

		<jsp:include page="../fragments/footer.jsp" />

	</div>
	</body>

</html>

src/main/webapp/WEB-INF/jsp/vets/vetList.jsp
<!DOCTYPE html> 

<%@ taglib prefix="spring" uri="http://www.springframework.org/tags" %>
<%@ taglib prefix="fmt" uri="http://java.sun.com/jsp/jstl/fmt" %>
<%@ taglib prefix="c" uri="http://java.sun.com/jsp/jstl/core" %>
<%@ taglib prefix="datatables" uri="http://github.com/dandelion/datatables" %>
<%@ taglib prefix="fn" uri="http://java.sun.com/jsp/jstl/functions" %>

<html lang="en">


<jsp:include page="../fragments/headTag.jsp"/>

<body>
<div class="container">
    <jsp:include page="../fragments/bodyHeader.jsp"/>

    <h2>Veterinarians</h2>

    <datatables:table id="vets" data="${vets.vetList}" cdn="true" row="vet" theme="bootstrap2" cssClass="table table-striped" paginate="false" info="false">
        <datatables:column title="Name">
            <c:out value="${vet.firstName} ${vet.lastName}"></c:out>
        </datatables:column>
        <datatables:column title="Specialties">
            <c:forEach var="specialty" items="${vet.specialties}">
                <c:out value="${specialty.name}"/>
            </c:forEach>
            <c:if test="${vet.nrOfSpecialties == 0}">none</c:if>
        </datatables:column>
        <datatables:column title="Days">
               <c:out value="${vet.days}"></c:out>
        </datatables:column>
        <datatables:column title="Email" cssStyle="width: 150px;" display="html">
               <spring:url value="/vet/{vetId}/email" var="vetUrl" >
                             <spring:param name="vetId" value="${vet.id}"/>

               </spring:url>
               <a href="${fn:escapeXml(vetUrl)}" alt="Sponsored by Aspose"><c:out value="${vet.email}" /></a>
        </datatables:column>

    </datatables:table>
    


            <td align="right">
            <img src="<spring:url value="/resources/images/aspose/asposeSmall.png" htmlEscape="true" />"alt="Sponsored by Aspose"/>
            <b>Export To:</b>
            </td>
            </tr>
            </table>

            <table>

                <tr>
                    <td><a href='<spring:url value="/vets/pdf/export" htmlEscape="true"/>'>
                    <img src="<spring:url value="/resources/images/aspose/aspose_pdf-for-java.jpg" htmlEscape="true" />"
                                                   alt="Sponsored by Aspose"/></a></td>
    <td><a href='<spring:url value="/vets/words/export" htmlEscape="true"/>'>
                    <img src="<spring:url value="/resources/images/aspose/aspose_words-for-java.jpg" htmlEscape="true" />"
                                                   alt="Sponsored by Aspose"/></a></td>
    <td><a href='<spring:url value="/vets/cells/export" htmlEscape="true"/>'>
                    <img src="<spring:url value="/resources/images/aspose/aspose_cells-for-java.jpg" htmlEscape="true" />"
                                                   alt="Sponsored by Aspose"/></a></td>
                </tr>
            </table>
            </br>

    <table class="table-buttons">
        <tr>

            <td>
                <a href="<spring:url value="/vets.xml" htmlEscape="true" />">View as XML</a>
            </td>


        </tr>
        <tr>
         <td>
                        <a href="<spring:url value="/vets.atom" htmlEscape="true" />">Subscribe to Atom feed</a>
                    </td>
                    </tr>
    </table>

     <tr>

    <jsp:include page="../fragments/footer.jsp"/>
</div>
</body>

</html>